@startuml
'https://plantuml.com/class-diagram

class ToDoListApplication{
+main()
+start()
}

ToDoListApplication --> ToDoListApplicationController

class ToDoListApplicationController{
public ToDoList toDoList

+initialize()
-addItemClick()
+addItemToLists()
-removeSelectedItemCLick
+setLoadListMenuTileClick
+setSaveListMenuTileClick
+clearAllItemsMenuClick()
+showIncompleteItemsOnly()
+showCompletedItemsOnly()
+showAllItems()
+addItemToLists()
+validateAndGetDescription()
+checkAndThenSetDate()
+checkRadioButton()
-addToStorage()
-refreshAllControls()
}

ToDoList <- ToDoListApplicationController

class ToDoList{
private ObservableList<Item> mainList

+getMainList()
+saveList()
+loadList()
}

Item <- ToDoList

class Item{
private int itemNum
private String description
private String dueDate
private String isComplete

+getDescription()
+setDescription()
+getDueDate()
+getIsComplete()
}
@enduml