@startuml
'https://plantuml.com/class-diagram

class ToDoListApplication{
+main()
+start()
}

ToDoListApplication --> ToDoListApplicationController

class ToDoListApplicationController{
private ArrayList<ToDoList> fullList
private ArrayList<ToDoList> selectedLists

+getFullList()
+setFullList()
+getSelectedList()
+setSelectedList()
+addToDoList()
+removeToDoList()
+renameToDoList()
+addToSelectedLists()
+removeFromSelectedLists()
+saveLists()
+loadLists()
}

ToDoList <- ToDoListApplicationController

class ToDoList{
private ArrayList<items> ToDoList

+getToDoList()
+setToDoList()

+addItem()
+removeItem()
+displayAllItems()
+displayCompletedItems()
+displayUncompletedItems()
+save()
}

Item <- ToDoList

class Item{
private int itemNum
private String description
private String dueDate
private bool isComplete

+getItemNum()
+setItemNum()
+getDescription()
+setDescription()
+getDueDate()
+setDueDate()
+getIsComplete()
+setIsComplete()

+changeDescription()
+changeDueDate()
+checkComplete()
+save()

}
@enduml